spring:
  profiles:
    active: dev
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: ${APP_ADMIN_USERNAME:admin}
      password: ${APP_ADMIN_PASSWORD:admin}

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET:exampleSecretKeyThatShouldBeReplacedInProduction}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION:3600000}
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:604800000}
  token-prefix: "Bearer "
  header-string: "Authorization"

logging:
  level:
    root: INFO
    com.praiseprep: DEBUG
    org.hibernate.SQL: DEBUG